name: Publish production version

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: yarn install

      - name: Update version
        run: bash ./updateVersion.sh

      - name: Deploy App Script
        run: bach ./publish.sh